In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'

import pandas as pd
# 스페이스바 한칸 이상 구분, 데이터에 열 이름이 없으므로 Header = None
df = pd.read_csv(url, sep='\s+', header = None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [5]:
type(df)

pandas.core.frame.DataFrame

In [7]:
from pandas import DataFrame

raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 
'age': [42, 52, 36, 24, 73], 
'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

df = pd.DataFrame(raw_data, columns=['age', 'city'])
df

   age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

In [9]:
path = './data/comp-data.csv'
df = pd.read_csv(path)
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [11]:
df.head(3)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000

In [13]:
df.tail(4)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [15]:
df.head().T

,0,1,2,3,4
account,211829,320563,648336,109996,121213
name,"Kerluke, Koepp and Hilpert",Walter-Trantow,"Bashirian, Kunde and Price","D'Amore, Gleichner and Bode",Bauch-Goldner
street,34456 Sean Highway,1311 Alvis Tunnel,62184 Schamberger Underpass Apt. 231,155 Fadel Crescent Apt. 144,7274 Marissa Common
city,New Jaycob,Port Khadijah,New Lilianland,Hyattburgh,Shanahanchester
state,Texas,NorthCarolina,Iowa,Maine,California
postal-code,28752,38365,76517,46021,49681
Jan,10000,95000,91000,45000,162000
Feb,62000,45000,120000,120000,120000
Mar,35000,35000,35000,10000,35000

In [29]:
df[['name', 'account', 'Jan']]

                                name  account     Jan
0         Kerluke, Koepp and Hilpert   211829   10000
1                     Walter-Trantow   320563   95000
2         Bashirian, Kunde and Price   648336   91000
3        D'Amore, Gleichner and Bode   109996   45000
4                      Bauch-Goldner   121213  162000
5   Williamson, Schumm and Hettinger   132971  150000
6                         Casper LLC   145068   62000
7                   Kovacek-Johnston   205217  145000
8                     Champlin-Morar   209744   70000
9                     Gerhold-Maggio   212303   70000
10       Goodwin, Homenick and Jerde   214098   45000
11                        Hahn-Moore   231907  150000
12      Frami, Anderson and Donnelly   242368  162000
13                       Walsh-Haley   268755   55000
14                     McDermott PLC   273274  150000

In [38]:
df[:3]

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000

In [48]:
type(df.iloc[1:,3:])

pandas.core.frame.DataFrame

In [49]:
df['Jan'] # 시리즈, Vector

0      10000
1      95000
2      91000
3      45000
4     162000
5     150000
6      62000
7     145000
8      70000
9      70000
10     45000
11    150000
12    162000
13     55000
14    150000
Name: Jan, dtype: int64

In [54]:
cond = df['Jan'] >= 150000
df[cond]

,account,name,street,city,state,postal-code,Jan,Feb,Mar
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [58]:
import pandas as pd # pandas 모듈 호출
import numpy as np # numpy 모듈 호출

ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings','kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
'Year': [2014, 2015, 2014, 2015, 2014, 2015, 2016, 2017, 2016, 2014, 2015, 2017],
'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

df = pd.DataFrame(ipl_data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [70]:
g = df.groupby(['Team', 'Year'])['Points'].sum()
g.groupby(level=0).sum()
# 머신러닝, 웹개발 비상

Team
Devils    1536
Kings     2285
Riders    3049
Royals    1505
kings      812
Name: Points, dtype: int64

In [71]:
import pandas as pd
raw_data = {
'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
'test_score': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

df_left = pd.DataFrame(raw_data, columns = ['subject_id', 'test_score'])
df_left

  subject_id  test_score
0          1          51
1          2          15
2          3          15
3          4          61
4          5          16
5          7          14
6          8          15
7          9           1
8         10          61
9         11          16

In [72]:
raw_data = {
            'subject_id': ['4', '5', '6', '7', '8'],
            'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
            'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

df_right = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_right

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [78]:
pd.merge(left=df_left, right=df_right, how='inner', on='subject_id')

  subject_id  test_score first_name last_name
0          4          61      Billy    Bonder
1          5          16      Brian     Black
2          7          14      Bryce     Brice
3          8          15      Betty    Btisan

In [79]:
pd.merge(left=df_left, right=df_right, how='outer', on='subject_id')

   subject_id  test_score first_name last_name
0           1        51.0        NaN       NaN
1          10        61.0        NaN       NaN
2          11        16.0        NaN       NaN
3           2        15.0        NaN       NaN
4           3        15.0        NaN       NaN
5           4        61.0      Billy    Bonder
6           5        16.0      Brian     Black
7           6         NaN       Bran   Balwner
8           7        14.0      Bryce     Brice
9           8        15.0      Betty    Btisan
10          9         1.0        NaN       NaN

In [80]:
import os
path = "./data"
filenames = [os.path.join(path, filename)
           for filename in os.listdir(path) if "sales" in filename]
print(filenames)#파일 이름

['./data\\sales-feb-2014.csv', './data\\sales-jan-2014.csv', './data\\sales-mar-2014.csv']

In [81]:
#filenames 기반으로 read_csv
df_list = [pd.read_csv(f) for f in filenames]

for df in df_list:
   print(type(df), len(df))

<class 'pandas.core.frame.DataFrame'> 108
<class 'pandas.core.frame.DataFrame'> 134
<class 'pandas.core.frame.DataFrame'> 142

In [90]:
data = pd.concat(df_list, axis=0)
data = data.reset_index(drop=True)

In [91]:
data[200:205]

,account number,name,sku,quantity,unit price,ext price,date
200,527099,Sanford and Sons,B1-05914,18,64.32,1157.76,2014-01-20 21:40:58
201,383080,Will LLC,B1-53636,37,14.40,532.80,2014-01-20 22:18:21
202,714466,Trantow-Barrows,S2-77896,48,37.80,1814.40,2014-01-21 05:05:38
203,218895,Kulas Inc,S2-16558,20,57.96,1159.20,2014-01-21 18:16:45
204,740150,Barton LLC,S2-16558,2,90.91,181.82,2014-01-21 21:21:01

In [95]:
data[['new', 'one']] = 0

In [96]:
data

,account number,name,sku,quantity,unit price,ext price,date,new,one
0,383080,Will LLC,B1-20000,7,33.69,235.83,2014-02-01 09:04:59,0,0
1,412290,Jerde-Hilpert,S1-27722,11,21.12,232.32,2014-02-01 11:51:46,0,0
2,412290,Jerde-Hilpert,B1-86481,3,35.99,107.97,2014-02-01 17:24:32,0,0
3,412290,Jerde-Hilpert,B1-20000,23,78.90,1814.70,2014-02-01 19:56:48,0,0
4,672390,Kuhn-Gusikowski,S1-06532,48,55.82,2679.36,2014-02-02 03:45:20,0,0
...,...,...,...,...,...,...,...,...,...
379,737550,"Fritsch, Russel and Anderson",B1-65551,12,56.24,674.88,2014-03-31 08:43:24,0,0
380,642753,Pollich LLC,S1-93683,21,92.57,1943.97,2014-03-31 11:37:34,0,0
381,412290,Jerde-Hilpert,B1-20000,30,22.38,671.40,2014-03-31 21:41:31,0,0
382,307599,"Kassulke, Ondricka and Metz",S2-16558,46,56.04,2577.84,2014-03-31 22:11:22,0,0
383,672390,Kuhn-Gusikowski,B1-04202,19,27.86,529.34,2014-03-31 23:13:14,0,0