In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {'A':[14.00,90.20,90.95,96.27,91.21],
     'B':[103.02,107.26,110.35,114.23,114.68], 
     'C':['big','small','big','small','small']})

df

       A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [2]:
Amin = df['A'].min() # 시리즈 객체(넘파이 배열 벡터)
Amax = df['A'].max() # 시리즈 객체(넘파이 배열 벡터)

nor = (df['A'] - Amin) / (Amax - Amin)

# AMin, AMax # 괄호가 생략된 튜플 출력
nor

0    0.000000
1    0.926219
2    0.935335
3    1.000000
4    0.938495
Name: A, dtype: float64

In [3]:
Bmean = df["B"].mean() # 평균
Bstd = df["B"].std() # 표준편차

z =  (df['B'] - Bmean) / Bstd

z

0   -1.405250
1   -0.540230
2    0.090174
3    0.881749
4    0.973556
Name: B, dtype: float64

In [4]:
edges = pd.DataFrame({'source': [0, 1, 2], 
                    'target': [2, 2, 3],
                    'weight': [3, 4, 5],
                    'color': ['red', 'blue', 'blue']})
edges

   source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [5]:
edges.dtypes

source     int64
target     int64
weight     int64
color     object
dtype: object

In [6]:
edges = pd.get_dummies(edges) # 저장되지 않음

In [7]:
key = {3: 'M', 4: 'L', 5: 'XL'}

# concat 수평은 그냥 붙이기
edges['size'] = edges['weight'].map(key)
pd.get_dummies(edges)

   source  target  weight  color_blue  color_red  size_L  size_M  size_XL
0       0       2       3       False       True   False    True    False
1       1       2       4        True      False    True   False    False
2       2       3       5        True      False   False   False     True

In [8]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 
                        'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon',
                     'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
            'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

df = pd.DataFrame(raw_data)
df

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [9]:
bins = [0, 25, 50, 75, 100]
name = ['Low', 'OK', 'Good', 'Great']
pd.cut(df['postTestScore'], bins, labels=name)

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): ['Low' < 'OK' < 'Good' < 'Great']

In [10]:
raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'], 
            'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'], 
            'age': [42, np.nan, 36, 24, 73], 
            'gender': ['m', np.nan, 'f', 'm', 'f'], 
            'preTestScore': [4, np.nan, np.nan, 2, 3],
            'postTestScore': [25, np.nan, np.nan, 62, 70]}

df = pd.DataFrame(raw_data)
df

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
1        NaN       NaN   NaN    NaN           NaN            NaN
2       Tina       Ali  36.0      f           NaN            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [11]:
df.isnull().sum() / len(df)

first_name       0.2
last_name        0.2
age              0.2
gender           0.2
preTestScore     0.4
postTestScore    0.4
dtype: float64

In [12]:
df

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
1        NaN       NaN   NaN    NaN           NaN            NaN
2       Tina       Ali  36.0      f           NaN            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [13]:
df.dropna(axis=0, how='all') # NaN 값이 있는 행 삭제, 기본값 axis = 0, 0은 행, 1은 열

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
2       Tina       Ali  36.0      f           NaN            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [14]:
df['location'] = np.nan
df

  first_name last_name   age gender  preTestScore  postTestScore  location
0      Jason    Miller  42.0      m           4.0           25.0       NaN
1        NaN       NaN   NaN    NaN           NaN            NaN       NaN
2       Tina       Ali  36.0      f           NaN            NaN       NaN
3       Jake    Milner  24.0      m           2.0           62.0       NaN
4        Amy     Cooze  73.0      f           3.0           70.0       NaN

In [15]:
df.dropna(axis=1, how='all', inplace=True) # inplace=True는 원본에 저장
# df.drop(axis=1, inplace=True) # 열 방향 삭제는 drop도 가능
df

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
1        NaN       NaN   NaN    NaN           NaN            NaN
2       Tina       Ali  36.0      f           NaN            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [16]:
df

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
1        NaN       NaN   NaN    NaN           NaN            NaN
2       Tina       Ali  36.0      f           NaN            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [17]:
df['preTestScore'].fillna(0) # 권장되지 않음
df.fillna({'preTestScore': 0}) # 권장됨, 일단 두 방식 모두 알아두기

  first_name last_name   age gender  preTestScore  postTestScore
0      Jason    Miller  42.0      m           4.0           25.0
1        NaN       NaN   NaN    NaN           0.0            NaN
2       Tina       Ali  36.0      f           0.0            NaN
3       Jake    Milner  24.0      m           2.0           62.0
4        Amy     Cooze  73.0      f           3.0           70.0

In [18]:
df.groupby('gender')['postTestScore'].mean()

gender
f    70.0
m    43.5
Name: postTestScore, dtype: float64

In [19]:
temp = df.groupby('gender')['postTestScore'].transform('mean')
df['postTestScore'].fillna(temp)

0    25.0
1     NaN
2    70.0
3    62.0
4    70.0
Name: postTestScore, dtype: float64

In [20]:
df1 = pd.read_csv('./data/titanic/train.csv')
df2 = pd.read_csv('./data/titanic/test.csv')

files = [df1, df2]
df = pd.concat(files, axis=0)
df = df.reset_index(drop=True)
df.head(3).T

,0,1,2
PassengerId,1,2,3
Survived,0.0,1.0,1.0
Pclass,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina"
Gender,male,female,female
Age,22.0,38.0,26.0
SibSp,1,1,0
Parch,0,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282
Fare,7.25,71.2833,7.925
Cabin,NaN,C85,NaN
Embarked,S,C,S

In [21]:
pd.options.display.float_format = '{:.2f}'.format

In [22]:
df.isnull().sum() / len(df)

PassengerId   0.00
Survived      0.32
Pclass        0.00
Name          0.00
Gender        0.00
Age           0.20
SibSp         0.00
Parch         0.00
Ticket        0.00
Fare          0.00
Cabin         0.77
Embarked      0.00
dtype: float64

In [23]:
df.drop('Cabin', axis=1, inplace=True) # 열 삭제

In [24]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [25]:
df.dropna(subset=['Survived'], inplace=True)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [26]:
len(df1)

891

In [27]:
df.groupby('Gender')['Age'].mean()

Gender
female   27.92
male     30.73
Name: Age, dtype: float64

In [28]:
df.groupby('Pclass')['Age'].mean()

Pclass
1   38.23
2   29.88
3   25.14
Name: Age, dtype: float64

In [29]:
m = df.groupby('Pclass')['Age'].transform('mean')
# df['Age'].fillna(m, inplace=True)
df.fillna({'Age':m}, inplace=True)
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Gender         0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [30]:
idx = df['Embarked'].isnull()
df[idx]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
61,62,1.00,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.00,NaN
829,830,1.00,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.00,0,0,113572,80.00,NaN

In [31]:
df.groupby('Embarked')['Embarked'].count()

Embarked
C    168
Q     77
S    644
Name: Embarked, dtype: int64

In [32]:
df.iloc[[61, 829], 10] = 'S'
df[idx]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
61,62,1.00,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.00,S
829,830,1.00,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.00,0,0,113572,80.00,S

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(3), int64(4), object(4)
memory usage: 83.5+ KB

In [38]:
pd.get_dummies(df['Gender'], prefix='Gender')

     Gender_female  Gender_male
0            False         True
1             True        False
2             True        False
3             True        False
4            False         True
..             ...          ...
886          False         True
887           True        False
888           True        False
889          False         True
890          False         True

[891 rows x 2 columns]

In [39]:
ctg_columns = ["Pclass", "Gender", "Embarked"]

for c in ctg_columns:
    onehot = pd.get_dummies(df[c], prefix=c)#해당 열 원핫인코딩
    
    #index로 병합하여 다시 df에 저장 df = pd.concat([df, onehot], axis=1)
    df = pd.merge(df,onehot, how="inner", left_index=True, right_index=True)

df.head(2).T

,0,1
PassengerId,1,2
Survived,0.00,1.00
Pclass,3,1
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th..."
Gender,male,female
Age,22.00,38.00
SibSp,1,1
Parch,0,0
Ticket,A/5 21171,PC 17599
Fare,7.25,71.28
Embarked,S,C
Pclass_1,False,True
Pclass_2,False,False
Pclass_3,True,False
Gender_female,False,True
Gender_male,True,False
Embarked_C,False,True
Embarked_Q,False,False
Embarked_S,True,False